import { TruthOrDareCategory, PromptType, TruthOrDareItem } from '../../../types/games';

export const TRUTH_OR_DARE_DATA: Record<
  TruthOrDareCategory,
  { name: string; icon: string; description: string; truths: TruthOrDareItem[]; dares: TruthOrDareItem[] }
> = {
  romantic: {
    name: 'Romantic & Sweet',
    icon: 'Heart',
    description: 'Heartwarming truths and tender romantic gestures.',
    truths: [
      { id: 'rt1', category: 'romantic', type: 'truth', text: 'What’s one small thing I do that still makes your heart flutter even over distance?', intensity: 1 },
      { id: 'rt2', category: 'romantic', type: 'truth', text: 'When did you first realize you were falling for me?', intensity: 1 },
      { id: 'rt3', category: 'romantic', type: 'truth', text: 'What’s your favorite memory of us so far and why does it still feel special?', intensity: 1 },
      { id: 'rt4', category: 'romantic', type: 'truth', text: 'If we woke up in the same bed tomorrow, what would you want to do first?', intensity: 2 },
      { id: 'rt5', category: 'romantic', type: 'truth', text: 'What’s something romantic I’ve said or done that you still think about?', intensity: 1 },
      { id: 'rt6', category: 'romantic', type: 'truth', text: 'How do you imagine our first real-life kiss after this distance?', intensity: 2 },
      { id: 'rt7', category: 'romantic', type: 'truth', text: 'What’s one thing you love most about the way I love you?', intensity: 1 },
      { id: 'rt8', category: 'romantic', type: 'truth', text: 'What’s a future moment with me you’re most looking forward to?', intensity: 1 },
      { id: 'rt9', category: 'romantic', type: 'truth', text: 'What’s the sweetest thing I’ve ever done for you long-distance?', intensity: 1 },
      { id: 'rt10', category: 'romantic', type: 'truth', text: 'If you could freeze one moment of us talking, which one would it be?', intensity: 1 },
      { id: 'rt11', category: 'romantic', type: 'truth', text: 'What’s something about my personality that feels like home to you?', intensity: 1 },
      { id: 'rt12', category: 'romantic', type: 'truth', text: 'How has being with me changed the way you think about love?', intensity: 2 },
      { id: 'rt13', category: 'romantic', type: 'truth', text: 'What’s one way I make you feel cherished even when we’re apart?', intensity: 1 },
      { id: 'rt14', category: 'romantic', type: 'truth', text: 'What’s a romantic gesture you’ve always wanted to experience with me?', intensity: 1 },
      { id: 'rt15', category: 'romantic', type: 'truth', text: 'What’s your favorite way I say “I love you” (words, actions, or energy)?', intensity: 1 },
      { id: 'rt16', category: 'romantic', type: 'truth', text: 'If we had a song that was “ours,” what would it be and why?', intensity: 1 },
      { id: 'rt17', category: 'romantic', type: 'truth', text: 'What’s one thing you miss most about the idea of being physically close?', intensity: 2 },
      { id: 'rt18', category: 'romantic', type: 'truth', text: 'What’s a quiet, everyday moment with me that you daydream about?', intensity: 1 },
      { id: 'rt19', category: 'romantic', type: 'truth', text: 'How do you feel most loved by me right now?', intensity: 1 },
      { id: 'rt20', category: 'romantic', type: 'truth', text: 'What’s one promise you’d want us to make to each other for the future?', intensity: 2 },
    ],
    dares: [
      { id: 'rd1', category: 'romantic', type: 'dare', text: 'Send a voice note describing one of your favorite things about my smile, voice, or laugh in detail.', intensity: 1 },
      { id: 'rd2', category: 'romantic', type: 'dare', text: 'Write and send a short love note as if we’re already living together.', intensity: 1 },
      { id: 'rd3', category: 'romantic', type: 'dare', text: 'On our next video call, look at me for 30 seconds without speaking and just smile.', intensity: 1 },
      { id: 'rd4', category: 'romantic', type: 'dare', text: 'Share your screen and show me a photo or playlist that reminds you of us, then explain why.', intensity: 1 },
      { id: 'rd5', category: 'romantic', type: 'dare', text: 'Send me three specific compliments about my personality you’ve never said out loud.', intensity: 1 },
      { id: 'rd6', category: 'romantic', type: 'dare', text: 'Plan and text me a detailed “perfect date night” for the next time we’re together.', intensity: 1 },
      { id: 'rd7', category: 'romantic', type: 'dare', text: 'Record a 30-second voice note of you saying three things you love about us.', intensity: 1 },
      { id: 'rd8', category: 'romantic', type: 'dare', text: 'Send a photo of something near you that makes you think of me and explain why.', intensity: 1 },
      { id: 'rd9', category: 'romantic', type: 'dare', text: 'On video call, tell me one romantic thing you’ve never said before while looking me in the eyes.', intensity: 2 },
      { id: 'rd10', category: 'romantic', type: 'dare', text: 'Write a short “missing you” message as if it’s a page from a love letter and send it.', intensity: 1 },
      { id: 'rd11', category: 'romantic', type: 'dare', text: 'Create a mini playlist of 3–5 songs that feel like us and share the link with explanations.', intensity: 1 },
      { id: 'rd12', category: 'romantic', type: 'dare', text: 'Send a voice note describing how you’d greet me at the airport or door.', intensity: 2 },
      { id: 'rd13', category: 'romantic', type: 'dare', text: 'On video call, blow me a slow, intentional kiss and hold eye contact for 10 seconds.', intensity: 1 },
      { id: 'rd14', category: 'romantic', type: 'dare', text: 'Text me the exact words you’d say if you could whisper them in my ear right now.', intensity: 2 },
      { id: 'rd15', category: 'romantic', type: 'dare', text: 'Share a screenshot of a past sweet message from me and tell me how it made you feel.', intensity: 1 },
      { id: 'rd16', category: 'romantic', type: 'dare', text: 'Describe in a voice note what our ideal lazy morning together would look like.', intensity: 1 },
      { id: 'rd17', category: 'romantic', type: 'dare', text: 'Send me a photo of the sky or view where you are and say “thinking of you under the same sky.”', intensity: 1 },
      { id: 'rd18', category: 'romantic', type: 'dare', text: 'On video call, say one thing you admire about how I love you.', intensity: 1 },
      { id: 'rd19', category: 'romantic', type: 'dare', text: 'Write and send a short future memory of us as if it already happened.', intensity: 2 },
      { id: 'rd20', category: 'romantic', type: 'dare', text: 'End the call by telling me one thing you’re grateful for about me today.', intensity: 1 },
    ],
  },
  spicy: {
    name: 'Spicy & Flirty',
    icon: 'Flame',
    description: 'Sensual questions and seductive dares to turn up the heat.',
    truths: [
      { id: 'st1', category: 'spicy', type: 'truth', text: 'What’s one thing you’d love to do to me (or have me do to you) the first night we’re finally together?', intensity: 3 },
      { id: 'st2', category: 'spicy', type: 'truth', text: 'Have you ever touched yourself thinking about me? What were you imagining?', intensity: 3 },
      { id: 'st3', category: 'spicy', type: 'truth', text: 'What’s your biggest turn-on when we’re on a video call?', intensity: 2 },
      { id: 'st4', category: 'spicy', type: 'truth', text: 'What’s a fantasy involving me that you’ve never fully told me?', intensity: 3 },
      { id: 'st5', category: 'spicy', type: 'truth', text: 'Where do you most want to be kissed the first time we’re together in person?', intensity: 2 },
      { id: 'st6', category: 'spicy', type: 'truth', text: 'What’s the sexiest message or photo you’ve almost sent me but held back?', intensity: 3 },
      { id: 'st7', category: 'spicy', type: 'truth', text: 'On a scale of 1–10, how badly do you want me right now, and what would push it higher?', intensity: 2 },
      { id: 'st8', category: 'spicy', type: 'truth', text: 'What’s one thing I do or say that instantly turns you on?', intensity: 2 },
      { id: 'st9', category: 'spicy', type: 'truth', text: 'What’s a position or scenario you keep imagining us in?', intensity: 3 },
      { id: 'st10', category: 'spicy', type: 'truth', text: 'How do you usually feel after a flirty or spicy conversation with me?', intensity: 2 },
      { id: 'st11', category: 'spicy', type: 'truth', text: 'What’s something you’ve wanted me to say to you during a private moment?', intensity: 2 },
      { id: 'st12', category: 'spicy', type: 'truth', text: 'What’s the most intense craving you’ve had for me while we’ve been apart?', intensity: 3 },
      { id: 'st13', category: 'spicy', type: 'truth', text: 'Have you ever replayed one of our conversations in your head in a spicy way?', intensity: 2 },
      { id: 'st14', category: 'spicy', type: 'truth', text: 'What’s one thing you’d want me to wear (or not wear) the first time we’re alone together?', intensity: 2 },
      { id: 'st15', category: 'spicy', type: 'truth', text: 'What’s a secret turn-on of yours that involves me?', intensity: 3 },
      { id: 'st16', category: 'spicy', type: 'truth', text: 'How do you like to be teased over text or call?', intensity: 2 },
      { id: 'st17', category: 'spicy', type: 'truth', text: 'What’s one place on your body you want my hands or mouth first?', intensity: 3 },
      { id: 'st18', category: 'spicy', type: 'truth', text: 'Have you ever gotten turned on just from hearing my voice? Describe it.', intensity: 2 },
      { id: 'st19', category: 'spicy', type: 'truth', text: 'What’s the boldest thing you’d be willing to do on a video call with me?', intensity: 3 },
      { id: 'st20', category: 'spicy', type: 'truth', text: 'What’s one spicy promise you’d want us to keep for when we’re finally together?', intensity: 3 },
    ],
    dares: [
      { id: 'sd1', category: 'spicy', type: 'dare', text: 'Send a voice note describing exactly what you’d do if I were in bed with you right now.', intensity: 3 },
      { id: 'sd2', category: 'spicy', type: 'dare', text: 'Take and send a photo of yourself in an outfit (or lack of one) that you know would drive me crazy.', intensity: 3 },
      { id: 'sd3', category: 'spicy', type: 'dare', text: 'On our next video call, whisper something dirty in my ear for 20 seconds.', intensity: 3 },
      { id: 'sd4', category: 'spicy', type: 'dare', text: 'Text me a detailed description of what you want me to do to you the next time we’re alone.', intensity: 3 },
      { id: 'sd5', category: 'spicy', type: 'dare', text: 'Send a short video of you biting your lip or looking at the camera in a seductive way.', intensity: 2 },
      { id: 'sd6', category: 'spicy', type: 'dare', text: 'Describe (text or voice) your ideal slow, teasing night with me from start to finish.', intensity: 3 },
      { id: 'sd7', category: 'spicy', type: 'dare', text: 'Change into something more revealing (or take something off) on video call and stay that way for the next few rounds.', intensity: 3 },
      { id: 'sd8', category: 'spicy', type: 'dare', text: 'Send a voice note of you saying my name the way you would if we were being intimate.', intensity: 3 },
      { id: 'sd9', category: 'spicy', type: 'dare', text: 'Text me three things you’d like me to do to you with my hands.', intensity: 3 },
      { id: 'sd10', category: 'spicy', type: 'dare', text: 'On video call, slowly run your fingers over your collarbone or neck while looking at me.', intensity: 2 },
      { id: 'sd11', category: 'spicy', type: 'dare', text: 'Send a photo of the outfit (or piece of clothing) you’d want me to take off you first.', intensity: 3 },
      { id: 'sd12', category: 'spicy', type: 'dare', text: 'Whisper a fantasy involving us on a voice note (keep it as detailed as you’re comfortable).', intensity: 3 },
      { id: 'sd13', category: 'spicy', type: 'dare', text: 'On video call, tell me one thing you’d do to make me lose control.', intensity: 3 },
      { id: 'sd14', category: 'spicy', type: 'dare', text: 'Send a text describing how you’d wake me up if we shared a bed.', intensity: 2 },
      { id: 'sd15', category: 'spicy', type: 'dare', text: 'Record a short video of you blowing a kiss and then biting your lip.', intensity: 2 },
      { id: 'sd16', category: 'spicy', type: 'dare', text: 'Tell me in a voice note exactly how you want to be touched when we’re finally together.', intensity: 3 },
      { id: 'sd17', category: 'spicy', type: 'dare', text: 'On video call, lean closer to the camera and say something that would make me blush.', intensity: 2 },
      { id: 'sd18', category: 'spicy', type: 'dare', text: 'Send a detailed text of the first 10 minutes after we lock the door.', intensity: 3 },
      { id: 'sd19', category: 'spicy', type: 'dare', text: 'Describe in a voice note the sounds or words you want to hear from me.', intensity: 3 },
      { id: 'sd20', category: 'spicy', type: 'dare', text: 'End with a voice note saying one spicy thing you’re looking forward to doing to me.', intensity: 3 },
    ],
  },
  deep: {
    name: 'Deep & Vulnerable',
    icon: 'Sparkles',
    description: 'Soulful questions and emotional connection builders.',
    truths: [
      { id: 'dt1', category: 'deep', type: 'truth', text: 'What’s one fear you have about our relationship that you haven’t fully shared?', intensity: 2 },
      { id: 'dt2', category: 'deep', type: 'truth', text: 'How has being with me changed the way you see yourself?', intensity: 2 },
      { id: 'dt3', category: 'deep', type: 'truth', text: 'What’s something from your past that still affects how you love or trust?', intensity: 2 },
      { id: 'dt4', category: 'deep', type: 'truth', text: 'When do you feel most emotionally safe with me, even across distance?', intensity: 1 },
      { id: 'dt5', category: 'deep', type: 'truth', text: 'What’s a part of yourself you’re still learning to accept, and how can I support that?', intensity: 2 },
      { id: 'dt6', category: 'deep', type: 'truth', text: 'If you could know one true thing about our future together, what would you want to know?', intensity: 2 },
      { id: 'dt7', category: 'deep', type: 'truth', text: 'What’s the hardest part of the distance for you emotionally, and what helps you through it?', intensity: 2 },
      { id: 'dt8', category: 'deep', type: 'truth', text: 'What’s one way I’ve helped you grow without even realizing it?', intensity: 1 },
      { id: 'dt9', category: 'deep', type: 'truth', text: 'What’s a vulnerability you’re still nervous to show me?', intensity: 2 },
      { id: 'dt10', category: 'deep', type: 'truth', text: 'How do you usually process difficult emotions, and do you want me more involved?', intensity: 2 },
      { id: 'dt11', category: 'deep', type: 'truth', text: 'What’s something you need from me that you haven’t clearly asked for?', intensity: 2 },
      { id: 'dt12', category: 'deep', type: 'truth', text: 'What’s a childhood memory that still shapes how you show love?', intensity: 2 },
      { id: 'dt13', category: 'deep', type: 'truth', text: 'When do you feel most proud of us as a couple?', intensity: 1 },
      { id: 'dt14', category: 'deep', type: 'truth', text: 'What’s one insecurity that shows up most in this relationship?', intensity: 2 },
      { id: 'dt15', category: 'deep', type: 'truth', text: 'How has long distance tested or strengthened your ability to trust?', intensity: 2 },
      { id: 'dt16', category: 'deep', type: 'truth', text: 'What’s something you’re afraid of losing if the distance lasts longer?', intensity: 2 },
      { id: 'dt17', category: 'deep', type: 'truth', text: 'What’s a quiet hope you have for us that you haven’t said out loud?', intensity: 2 },
      { id: 'dt18', category: 'deep', type: 'truth', text: 'How do you want to be comforted when you’re struggling?', intensity: 1 },
      { id: 'dt19', category: 'deep', type: 'truth', text: 'What’s one truth about yourself you want me to fully understand?', intensity: 2 },
      { id: 'dt20', category: 'deep', type: 'truth', text: 'What does “home” feel like to you when you think of us?', intensity: 1 },
    ],
    dares: [
      { id: 'dd1', category: 'deep', type: 'dare', text: 'Share a voice note about a moment you felt really proud of us as a couple.', intensity: 1 },
      { id: 'dd2', category: 'deep', type: 'dare', text: 'Tell me (text or voice) one insecurity you have and let me respond with honesty and care.', intensity: 2 },
      { id: 'dd3', category: 'deep', type: 'dare', text: 'On video call, look at me and finish the sentence: “One thing I need from you more of is…”', intensity: 2 },
      { id: 'dd4', category: 'deep', type: 'dare', text: 'Send me a message describing a time I made you feel deeply understood.', intensity: 1 },
      { id: 'dd5', category: 'deep', type: 'dare', text: 'Share one personal goal or dream you haven’t talked about much, and how I fit into it.', intensity: 2 },
      { id: 'dd6', category: 'deep', type: 'dare', text: 'Write a short message as if you’re talking to your future self about us, then send it to me.', intensity: 2 },
      { id: 'dd7', category: 'deep', type: 'dare', text: 'On video call, tell me one thing you’re still learning to accept about yourself.', intensity: 2 },
      { id: 'dd8', category: 'deep', type: 'dare', text: 'Send a voice note explaining a fear you have and what would help you feel safer.', intensity: 2 },
      { id: 'dd9', category: 'deep', type: 'dare', text: 'Share a screenshot or memory of a moment that made you feel especially close to me.', intensity: 1 },
      { id: 'dd10', category: 'deep', type: 'dare', text: 'On video call, say one thing you’ve been holding back but want me to know.', intensity: 2 },
      { id: 'dd11', category: 'deep', type: 'dare', text: 'Write and send three things you appreciate about how I handle hard conversations.', intensity: 1 },
      { id: 'dd12', category: 'deep', type: 'dare', text: 'Tell me in a voice note how you want me to support you when you’re overwhelmed.', intensity: 1 },
      { id: 'dd13', category: 'deep', type: 'dare', text: 'On video call, look at me and share one thing that still feels vulnerable to admit.', intensity: 2 },
      { id: 'dd14', category: 'deep', type: 'dare', text: 'Send a message about a time you felt really safe opening up to me.', intensity: 1 },
      { id: 'dd15', category: 'deep', type: 'dare', text: 'Share one personal boundary you want us to protect and why it matters.', intensity: 2 },
      { id: 'dd16', category: 'deep', type: 'dare', text: 'On video call, finish the sentence: “Sometimes I worry that…”', intensity: 2 },
      { id: 'dd17', category: 'deep', type: 'dare', text: 'Send a voice note describing what emotional safety with me feels like.', intensity: 1 },
      { id: 'dd18', category: 'deep', type: 'dare', text: 'Tell me one way I can love you better that I might not already know.', intensity: 2 },
      { id: 'dd19', category: 'deep', type: 'dare', text: 'Share a short reflection on how this relationship has changed you.', intensity: 2 },
      { id: 'dd20', category: 'deep', type: 'dare', text: 'End by telling me one deep truth about how you feel about us right now.', intensity: 2 },
    ],
  },
  fun: {
    name: 'Playful',
    icon: 'Laugh',
    description: 'Lighthearted laughs, goofy challenges, and playful connection.',
    truths: [
      { id: 'ft1', category: 'fun', type: 'truth', text: 'What’s the silliest thing you’ve done because you missed me?', intensity: 1 },
      { id: 'ft2', category: 'fun', type: 'truth', text: 'If we had a couple’s superpower, what would it be and why?', intensity: 1 },
      { id: 'ft3', category: 'fun', type: 'truth', text: 'What’s a ridiculous pet name you’ve almost called me?', intensity: 1 },
      { id: 'ft4', category: 'fun', type: 'truth', text: 'What’s the funniest misunderstanding we’ve had because of the distance?', intensity: 1 },
      { id: 'ft5', category: 'fun', type: 'truth', text: 'If you had to describe our relationship as a movie genre, what would it be?', intensity: 1 },
      { id: 'ft6', category: 'fun', type: 'truth', text: 'What’s one embarrassing habit of yours I still don’t know about?', intensity: 1 },
      { id: 'ft7', category: 'fun', type: 'truth', text: 'What’s the weirdest thing you’ve googled because of something we talked about?', intensity: 1 },
      { id: 'ft8', category: 'fun', type: 'truth', text: 'If we were cartoon characters, who would we be?', intensity: 1 },
      { id: 'ft9', category: 'fun', type: 'truth', text: 'What’s a funny habit of mine that secretly amuses you?', intensity: 1 },
      { id: 'ft10', category: 'fun', type: 'truth', text: 'What’s the most ridiculous thing you’ve imagined us doing together?', intensity: 1 },
      { id: 'ft11', category: 'fun', type: 'truth', text: 'If our relationship had a theme song that wasn’t romantic, what would it be?', intensity: 1 },
      { id: 'ft12', category: 'fun', type: 'truth', text: 'What’s a random skill you think we’d be chaotic at together?', intensity: 1 },
      { id: 'ft13', category: 'fun', type: 'truth', text: 'What’s the funniest way you’ve tried to feel closer to me while apart?', intensity: 1 },
      { id: 'ft14', category: 'fun', type: 'truth', text: 'If we had a secret handshake, what would it involve?', intensity: 1 },
      { id: 'ft15', category: 'fun', type: 'truth', text: 'What’s one silly fear you have about meeting in person for the first time?', intensity: 1 },
      { id: 'ft16', category: 'fun', type: 'truth', text: 'What’s a meme or joke that instantly makes you think of us?', intensity: 1 },
      { id: 'ft17', category: 'fun', type: 'truth', text: 'If we were stuck in an elevator for an hour, how would we pass the time?', intensity: 1 },
      { id: 'ft18', category: 'fun', type: 'truth', text: 'What’s the most chaotic date idea you’ve ever had for us?', intensity: 1 },
      { id: 'ft19', category: 'fun', type: 'truth', text: 'What’s a funny nickname the universe should have given us as a couple?', intensity: 1 },
      { id: 'ft20', category: 'fun', type: 'truth', text: 'What’s one playful thing you want us to do the first time we’re together?', intensity: 1 },
    ],
    dares: [
      { id: 'fd1', category: 'fun', type: 'dare', text: 'Send a voice note of you singing (badly or well) a few lines of a song that reminds you of me.', intensity: 1 },
      { id: 'fd2', category: 'fun', type: 'dare', text: 'Do your best impression of me on video call for 20 seconds.', intensity: 1 },
      { id: 'fd3', category: 'fun', type: 'dare', text: 'Send me a meme or reaction image that perfectly captures how you’re feeling about me right now, then explain it.', intensity: 1 },
      { id: 'fd4', category: 'fun', type: 'dare', text: 'On video call, try to make me laugh without speaking for 30 seconds (faces and gestures only).', intensity: 1 },
      { id: 'fd5', category: 'fun', type: 'dare', text: 'Text me your phone’s autocomplete predictions when you start typing my name or a pet name.', intensity: 1 },
      { id: 'fd6', category: 'fun', type: 'dare', text: 'Create and send a short “day in the life with you” story as if we lived together (make it chaotic or cute).', intensity: 1 },
      { id: 'fd7', category: 'fun', type: 'dare', text: 'On video call, do a dramatic reenactment of how you react when you see my name pop up.', intensity: 1 },
      { id: 'fd8', category: 'fun', type: 'dare', text: 'Send a voice note in a funny accent saying something sweet or random.', intensity: 1 },
      { id: 'fd9', category: 'fun', type: 'dare', text: 'Share your screen and show me the weirdest thing currently in your camera roll, then explain.', intensity: 1 },
      { id: 'fd10', category: 'fun', type: 'dare', text: 'On video call, invent and perform a 10-second “missing you” dance.', intensity: 1 },
      { id: 'fd11', category: 'fun', type: 'dare', text: 'Text me three ridiculous couple goals that only we would understand.', intensity: 1 },
      { id: 'fd12', category: 'fun', type: 'dare', text: 'Send a photo of you making your silliest face with a caption about us.', intensity: 1 },
      { id: 'fd13', category: 'fun', type: 'dare', text: 'On video call, try to say a tongue-twister while looking serious.', intensity: 1 },
      { id: 'fd14', category: 'fun', type: 'dare', text: 'Create a fake movie title and tagline about our relationship and send it.', intensity: 1 },
      { id: 'fd15', category: 'fun', type: 'dare', text: 'Send a voice note of you narrating a dramatic trailer for “The Long Distance Saga.”', intensity: 1 },
      { id: 'fd16', category: 'fun', type: 'dare', text: 'On video call, mirror my facial expressions for 20 seconds.', intensity: 1 },
      { id: 'fd17', category: 'fun', type: 'dare', text: 'Text me the most unhinged compliment you can think of.', intensity: 1 },
      { id: 'fd18', category: 'fun', type: 'dare', text: 'Send a short video of you attempting to wink, blow a kiss, and look mysterious in one go.', intensity: 1 },
      { id: 'fd19', category: 'fun', type: 'dare', text: 'On video call, invent a secret handshake and teach it to me through the screen.', intensity: 1 },
      { id: 'fd20', category: 'fun', type: 'dare', text: 'End by sending a voice note of you saying something completely random and wholesome about us.', intensity: 1 },
    ],
  },
};

export function getRandomPrompt(
  category: TruthOrDareCategory,
  type: PromptType,
  excludeIds: string[] = []
): TruthOrDareItem {
  const pool = TRUTH_OR_DARE_DATA[category][type === 'truth' ? 'truths' : 'dares'];
  const candidates = pool.filter((p) => !excludeIds.includes(p.id));
  const selectedList = candidates.length > 0 ? candidates : pool;
  const randomIndex = Math.floor(Math.random() * selectedList.length);
  return selectedList[randomIndex];
}
