export const COUPLE_WORD_LIST: string[] = [
  'HEART', 'SWEET', 'LOVER', 'SMILE', 'DREAM', 'TRUST', 'DATES', 'BLUSH',
  'KISSY', 'MAGIC', 'CHARM', 'HONEY', 'ANGEL', 'CANDY', 'SPARK', 'WARMTH',
  'PEACE', 'ROSES', 'TOUCH', 'DEVOT', 'ADORE', 'BLOOM', 'FLAME', 'UNITY',
  'BLISS', 'CHAPS', 'SOULS', 'BEAMS', 'LIGHT', 'DANCE', 'HAPPY', 'SHINE'
];

export const VALID_GUESS_DICTIONARY = new Set([
  ...COUPLE_WORD_LIST,
  'ABOUT', 'ABOVE', 'AFTER', 'AGAIN', 'ALONE', 'ALONG', 'AMONG', 'BEACH',
  'BEGIN', 'BLACK', 'BRAIN', 'BREAD', 'BRING', 'BROWN', 'BUILD', 'CARRY',
  'CAUSE', 'CHAIN', 'CHAIR', 'CHECK', 'CHILD', 'CLEAN', 'CLEAR', 'CLOCK',
  'CLOSE', 'CLOUD', 'COACH', 'COAST', 'COLOR', 'COULD', 'COVER', 'CRAFT',
  'CROSS', 'CROWD', 'CROWN', 'DAILY', 'DEATH', 'DRIVE', 'EARTH', 'EARLY',
  'EMPTY', 'ENTER', 'EQUAL', 'EVENT', 'EVERY', 'FAITH', 'FIELD', 'FIFTH',
  'FIGHT', 'FINAL', 'FIRST', 'FLOOR', 'FOCUS', 'FORCE', 'FRONT', 'GIVEN',
  'GLASS', 'GRAND', 'GRASS', 'GREAT', 'GREEN', 'GROUP', 'GUARD', 'GUESS',
  'HABIT', 'HANDS', 'HEAVY', 'HELLO', 'HONOR', 'HORSE', 'HOTEL', 'HOUSE',
  'HUMAN', 'IMAGE', 'JEWEL', 'JUDGE', 'KNIFE', 'LAUGH', 'LAYER', 'LEARN',
  'LEAVE', 'LEVEL', 'LUNCH', 'MARRY', 'MATCH', 'MAYBE', 'MONEY', 'MONTH',
  'MOUTH', 'MUSIC', 'NIGHT', 'NOBLE', 'NORTH', 'NURSE', 'OCEAN', 'OFFER',
  'ORDER', 'OTHER', 'PAINT', 'PANEL', 'PAPER', 'PARTY', 'PEACE', 'PETER',
  'PHONE', 'PHOTO', 'PIECE', 'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'PLANE',
  'PLANT', 'PLATE', 'POINT', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE',
  'PRIZE', 'PROOF', 'QUEEN', 'QUICK', 'QUIET', 'RADIO', 'RAISE', 'RANGE',
  'REACH', 'READY', 'RIVER', 'ROUND', 'ROUTE', 'ROYAL', 'SCENE', 'SCORE',
  'SENSE', 'SERVE', 'SEVEN', 'SHALL', 'SHARE', 'SHIRT', 'SHOCK', 'SHOOT',
  'SHORT', 'SIGHT', 'SKILL', 'SLEEP', 'SMART', 'SOLID', 'SOUND', 'SOUTH',
  'SPACE', 'SPEAK', 'SPEED', 'SPEND', 'SPORT', 'STAFF', 'STAGE', 'STAND',
  'START', 'STATE', 'STEAM', 'STEEL', 'STICK', 'STILL', 'STOCK', 'STONE',
  'STORE', 'STORM', 'STORY', 'STYLE', 'SUGAR', 'TABLE', 'TASTE', 'TEACH',
  'THANK', 'THEME', 'THERE', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE',
  'TIGHT', 'TIMES', 'TIRED', 'TITLE', 'TODAY', 'TOPIC', 'TOTAL', 'TOWER',
  'TRACK', 'TRADE', 'TRAIN', 'TREAT', 'TRUCK', 'TRULY', 'TRUTH', 'TWICE',
  'UNDER', 'UNION', 'UNTIL', 'VALUE', 'VIDEO', 'VISIT', 'VOICE', 'WASTE',
  'WATCH', 'WATER', 'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE', 'WHOLE',
  'WOMAN', 'WORLD', 'WORRY', 'WORTH', 'WOULD', 'WRITE', 'WRONG', 'YEARS',
  'YOUTH', 'LOVED', 'KISSES', 'CUPID', 'ROMAN', 'FAVOR', 'GRACE', 'SHINE'
]);
